<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ADOverhaul2022</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Interceptor.Ref" />
    <None Remove="Tests.Consumer" />
    <EmbeddedResource Include="Interceptor.Ref" LogicalName="Interceptor.Ref" />
    <EmbeddedResource Include="Tests.Consumer" LogicalName="Tests.Consumer" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="VRC.Dynamics">
      <HintPath>../../deps/vrchat/VRC.Dynamics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../deps/unity/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="VRC.SDK3.Dynamics.PhysBone">
      <HintPath>../../deps/vrchat/VRC.SDK3.Dynamics.PhysBone.dll</HintPath>
    </Reference>
    <Reference Include="VRCSDK3A">
      <HintPath>../../deps/vrchat/VRCSDK3A.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor">
      <HintPath>../../deps/unity/UnityEditor.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>../../deps/unity/UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../deps/unity/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>../../deps/unity/UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="VRC.SDK3.Dynamics.Contact">
      <HintPath>../../deps/vrchat/VRC.SDK3.Dynamics.Contact.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>../../deps/unity/UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>../../deps/unity/UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>../../deps/unity/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>../../deps/unity/UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>