<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ControllerEditor</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Param.Wrapper" />
    <None Remove="Tests.Record" />
    <EmbeddedResource Include="Param.Wrapper" LogicalName="Param.Wrapper" />
    <EmbeddedResource Include="Tests.Record" LogicalName="Tests.Record" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>../../deps/unity/UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../deps/unity/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>../../deps/unity/UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor">
      <HintPath>../../deps/unity/UnityEditor.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>../../deps/unity/UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../deps/unity/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor.Graphs">
      <HintPath>../../deps/unity/UnityEditor.Graphs.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>../../deps/unity/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="VRCSDK3A">
      <HintPath>../../deps/vrchat/VRCSDK3A.dll</HintPath>
    </Reference>
    <Reference Include="VRC.SDK3.Dynamics.Contact">
      <HintPath>../../deps/vrchat/VRC.SDK3.Dynamics.Contact.dll</HintPath>
    </Reference>
    <Reference Include="VRC.SDK3.Dynamics.PhysBone">
      <HintPath>../../deps/vrchat/VRC.SDK3.Dynamics.PhysBone.dll</HintPath>
    </Reference>
    <Reference Include="VRC.Dynamics">
      <HintPath>../../deps/vrchat/VRC.Dynamics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>../../deps/unity/UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>../../deps/unity/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>../../deps/unity/UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="VRCSDKBase">
      <HintPath>../../deps/vrchat/VRCSDKBase.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>